name: Docker Image Builder
on:
  workflow_dispatch:
  repository_dispatch:
    types: [on-update]

jobs:
  Docker_Image_Builder:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set Image Version
        run: |
          echo "VERSION=$(date +"%Y%m%d")" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nestingdns:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nestingdns:${{ env.VERSION }}
          
      - name: Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 30
          keep_minimum_runs: 10